### ISSUE TITLE
0.1 open-source release

### ISSUE THREAD

**Issue by Jonplussed** [ThoughtLeadr/hsyslog-udp#2]
The API for hsyslog-udp seems stable and the code is tested. Any changes would be for performance or stability purposes. I believe this is ready to be open-sourced and pushed to Hackage.

**Comment by Jonplussed** [comment]
@Shakakai @qrilka @k-bx anything else you'd like changed before we open-source this?

**Comment by qrilka** [comment]
LGTM

**Comment by k-bx** [comment]
+1, nothing from me, thanks

**Comment by Jonplussed** [comment]
I've created the initial Hackage release [v0.1.1](https://github.com/ThoughtLeadr/hsyslog-udp/releases/tag/v0.1.1).
